[2017-04-14 08:11:46.419] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index
request client ip:  ::1
request query:  {}
response time: 1160
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at ConnectionManager.connect (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:247:43)
From previous event:
    at Promise.then (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\qinxy\Desktop\node\koa2_all\model\logic_model\user.js:5:58)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-router\lib\router.js:326:16
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at app.use (C:\Users\qinxy\Desktop\node\koa2_all\app.js:42:9)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at app.use (C:\Users\qinxy\Desktop\node\koa2_all\app.js:30:11)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at send.then.done (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-14 08:30:58.951] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index
request client ip:  ::1
request query:  {}
response time: 227
err name: SequelizeDatabaseError
err message: ER_BAD_FIELD_ERROR: Unknown column 'updatedAt' in 'field list'
err stack: SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'updatedAt' in 'field list'
    at Query.formatError (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
From previous event:
    at Query.run (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\query.js:39:17)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\sequelize.js:849:20
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\retry-as-promised\index.js:40:21
From previous event:
    at retryAsPromised (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\retry-as-promised\index.js:30:10)
    at ConnectionManager.<anonymous> (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\sequelize.js:848:12)
From previous event:
    at Promise.then (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\qinxy\Desktop\node\koa2_all\model\logic_model\user.js:5:58)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-router\lib\router.js:326:16
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at app.use (C:\Users\qinxy\Desktop\node\koa2_all\app.js:43:9)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at app.use (C:\Users\qinxy\Desktop\node\koa2_all\app.js:30:11)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at send.then.done (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-14 08:31:42.833] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index
request client ip:  ::1
request query:  {}
response time: 42
err name: SequelizeDatabaseError
err message: ER_BAD_FIELD_ERROR: Unknown column 'updatedAt' in 'field list'
err stack: SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'updatedAt' in 'field list'
    at Query.formatError (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
From previous event:
    at Query.run (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\dialects\mysql\query.js:39:17)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\sequelize.js:849:20
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\retry-as-promised\index.js:40:21
From previous event:
    at retryAsPromised (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\retry-as-promised\index.js:30:10)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\sequelize.js:848:12
From previous event:
    at Promise.then (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\qinxy\Desktop\node\koa2_all\model\logic_model\user.js:5:58)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-router\lib\router.js:326:16
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at app.use (C:\Users\qinxy\Desktop\node\koa2_all\app.js:43:9)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at app.use (C:\Users\qinxy\Desktop\node\koa2_all\app.js:30:11)
    at dispatch (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-compose\index.js:45:18)
    at send.then.done (C:\Users\qinxy\Desktop\node\koa2_all\node_modules\koa-static\index.js:43:20)
*************** error log end ***************

