[2017-04-13 23:38:13.992] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 1680
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:125:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:5:58)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:326:16
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at app.use (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\app.js:30:11)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at send.then.done (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.0.0@koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-13 23:38:23.280] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 1017
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:125:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:5:58)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:326:16
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at app.use (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\app.js:30:11)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at send.then.done (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.0.0@koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-13 23:43:16.880] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 1109
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:125:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:5:58)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:326:16
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at app.use (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\app.js:30:11)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at send.then.done (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.0.0@koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-13 23:43:39.368] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 1121
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:125:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:5:58)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:326:16
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at app.use (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\app.js:30:11)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at send.then.done (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.0.0@koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-13 23:45:58.501] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 1105
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:125:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:5:58)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:326:16
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at app.use (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\app.js:30:11)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at send.then.done (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.0.0@koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-13 23:47:10.133] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 1110
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:125:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:5:58)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:326:16
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at app.use (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\app.js:30:11)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at send.then.done (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.0.0@koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-13 23:52:42.458] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 1133
err name: SequelizeConnectionRefusedError
err message: connect ECONNREFUSED 127.0.0.1:3306
err stack: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:80:20)
    at Handshake.Sequence.end (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Protocol.handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\protocol\Protocol.js:364:14)
    at Connection._handleNetworkError (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\mysql\lib\Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\debuggability.js:397:19)
    at Promise._then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:232:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.5.0@bluebird\js\release\promise.js:125:17)
    at Promise.then (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\promise.js:21:17)
    at Model.findAll (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\sequelize\lib\model.js:1395:6)
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:5:58)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:326:16
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.7.1.1@koa-router\lib\router.js:331:31)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at app.use (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\app.js:30:11)
    at dispatch (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.2.1@koa-compose\index.js:45:18)
    at send.then.done (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\node_modules\.3.0.0@koa-static\index.js:43:20)
*************** error log end ***************

[2017-04-13 23:53:18.552] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 378
err name: TypeError
err message: Cannot set property 'getUsers' of undefined
err stack: TypeError: Cannot set property 'getUsers' of undefined
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:6:28)
*************** error log end ***************

[2017-04-13 23:53:47.553] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 140
err name: TypeError
err message: Cannot set property 'getUsers' of undefined
err stack: TypeError: Cannot set property 'getUsers' of undefined
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:6:28)
*************** error log end ***************

[2017-04-13 23:54:57.762] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 52
err name: TypeError
err message: Cannot set property 'getUsers' of undefined
err stack: TypeError: Cannot set property 'getUsers' of undefined
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:6:28)
*************** error log end ***************

[2017-04-13 23:55:48.532] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 145
err name: TypeError
err message: Cannot set property 'getUsers' of undefined
err stack: TypeError: Cannot set property 'getUsers' of undefined
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:6:28)
*************** error log end ***************

[2017-04-13 23:55:56.912] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /index/
request client ip:  ::1
request query:  {}
response time: 175
err name: TypeError
err message: Cannot set property 'getUsers' of undefined
err stack: TypeError: Cannot set property 'getUsers' of undefined
    at user.getUsers (C:\Users\12156\Desktop\js\node\ko2\HelloKoa2\mobel\logic_model\user.js:7:28)
*************** error log end ***************

